### ISSUE TITLE
Samples on the docs.ms samples browser

### ISSUE THREAD

**Issue by cartermp** [dotnet/samples#1827]
I noticed that the [101 LINQ samples](https://github.com/dotnet/samples/tree/master/core/linq/csharp) aren't on the samples site: https://docs.microsoft.com/samples/browse/?term=linq

Are there other missing?

**Comment by BillWagner** [comment]
@cartermp I ported all these to the [try-samples](https://github.com/dotnet/try-samples/tree/master/101-linq-samples) repo, using the local try.net experience.

I do need to point these to the new browser.
