### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/samples#3604]
The current repo description is:

> Sample code and snippets used in the .NET documentation

AFAIK, docs now is independent from samples. Isn't this repo only used for Samples Browser now?

**Comment by Thraka** [comment]
Did you mean independent from snippets? I think we can close this issue as your PR corrected the wording.

**Comment by Youssef1313** [comment]
The repo description cannot be updated in a PR.
The other PR was related to this, but doesn't fix it.

**Comment by Youssef1313** [comment]
@Thraka 
![IMG_20200520_195235](https://user-images.githubusercontent.com/31348972/82480061-88ac6d80-9ad3-11ea-9fc0-cdbc33ffbdbf.jpg)
