### ISSUE TITLE
Problem running Excel sample with .NET 5

### ISSUE THREAD

**Issue by imekon** [dotnet/samples#4065]
**Issue description**

Using Excel sample with .NET 5 results in an exception - FileNoteFound

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong>

```console
C:\Users\pgoodwin>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
</details>

I took your sample here for Excel and built a version with .NET 5. When I try to run it, I get the following exception:

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

I added a COM reference to Microsoft Excel 16.0 Object Library, I also have Microsoft Office installed. If I build a similar sample with .NET Framework 4.7 it works fine.

What do I need to do to make this work? Which file is missing?

This is the content of the Debug directory:

 Directory of D:\Projects\ExcelSample\bin\Debug\net5.0

16/12/2020  10:27    <DIR>          .
16/12/2020  10:27    <DIR>          ..
16/12/2020  10:18               924 ExcelSample.deps.json
16/12/2020  10:18             6,144 ExcelSample.dll
16/12/2020  10:18           142,848 ExcelSample.exe
16/12/2020  10:18             9,756 ExcelSample.pdb
16/12/2020  10:18               180 ExcelSample.runtimeconfig.dev.json
16/12/2020  10:18               147 ExcelSample.runtimeconfig.json
16/12/2020  10:27                 0 files.txt
16/12/2020  10:17         1,707,520 Interop.Microsoft.Office.Interop.Excel.dll
16/12/2020  10:16    <DIR>          ref
               8 File(s)      1,867,519 bytes

**Comment by adegeo** [comment]
Do you have a link to the specific example?

**Comment by imekon** [comment]
It's in this repository, core\extensions\ExcelDemo

If I take the project there directly, then build and run it, it works fine.

If I switch to .NET 5, it works fine.

If I create a console app with VS 2019 and change it to .NET 5, add a COM reference to Microsoft Excel 16.0 Object Library and use the same code as the sample, then it fails with the File Not Found exception.

Here's the project file generated with VS 2019:

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="Microsoft.Office.Excel.dll">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>9</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>00020813-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
  </ItemGroup>

</Project>
`

I had a look at the project file for the demo and there are more COM objects present than in my project. I added Microsoft Office Core but that didn't help and I've no idea what VBIDE is. Which COM objects do I need to add to my project to make this work: "Could not load file or assembly 'office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'. The system cannot find the file specified."

**Comment by imekon** [comment]
OK, I changed the settings on the COM objects for WrapperTool from "tblimp" to "primary" and now it works. Seems like VS 2019 is using the wrong setting for .NET 5 and COM objects?

**Comment by adegeo** [comment]
I wouldn't be able to say. But as seeing you're code is OK now, I'll close this issue. Sorry for the delay.
