### ISSUE TITLE
AppWithPlugin sample intended older Json.Net verison got bumped by dependabot

### ISSUE THREAD

**Issue by Mrxx99** [dotnet/samples#4307]
**Issue description**

The sample AppWithPlugin shows intentionally loading two plugins with different versions of Newtonsoft.Json.
The project samples/core/extensions/AppWithPlugin/OldJsonPlugin initially had an older version (10.0.3) of Newtonsoft.Json to showcase loading different plugins with different versions of the same dependency but the version got updated by the dependabot. Now both sample projects (OldJsonPlugin and JsonPlugin) have the latest (and same) verison of Netwonsoft.Json.

**Target framework**

- [x] .NET Core 5
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by jaumemilian** [comment]
I was a bit surprised seeing the same Newtonsoft version. Thanks to your commend I understand I has been an error

**Comment by Mrxx99** [comment]
fixed by #4545
