### ISSUE TITLE
Sample supposed to be in samples browser isn't there

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/samples#4723]
Looks like the samples were dropped after #4583, I can't find them live.

After figuring out the correct way to have the sample with the download ZIP button, every sample in the repo will need to get fixed. See https://github.com/dotnet/docs/issues/23380.

**Comment by Youssef1313** [comment]
cc @adegeo

**Comment by adegeo** [comment]
@Youssef1313 I would check back in like a week or two. There was an infrastructure issue where the products we were using were excluded and thus removed from the browser. I think yesterday it was fixed by the team.

**Comment by gewarren** [comment]
Also, using `extendedZipContent` with null values is not longer supported, and means a sample won't be indexed into the browser.

**Comment by adegeo** [comment]
Just checked and these are in the browser. This issue can probably be closed.

**Comment by Youssef1313** [comment]
@adegeo Yeah they are there because `extendedZipContent` was removed. But the download ZIP button isn't.

I wonder if we could use `extendedZipContent` with non-null value (e.g, include the root README or whatever file so the download button is there).

**Comment by adegeo** [comment]
Possibly. I randomly clicked on about 20 samples before I found one with a download button. That section was set to something in the repo. It seems like a silly requirement.
