### ISSUE TITLE
Please update samples for .NET 6.0

### ISSUE THREAD

**Issue by phume03** [dotnet/samples#4953]
## Please update .Net 4.0 samples to .Net 6.0 (LTS)

Presently, .Net is at v5.0 (current) and will move to v6.0 after February 2022. So, this code is outdated and will not run correctly on the newer versions of .Net.

When run on VS2022, the code samples claims that the target framework is not supported. Then, prompts the user to either download the targeted .Net 4.0 framework, to run with .Net 4.8 (upgrade), or to abandon running the samples. The download option leads to a dotnet sdk page, where 4.0 is missing or not available. Upgrading is seemingly done in place but the application crashes at several points during running.

Also worth noting is that Vs2022 does not offer the option to install v4.0 of .Net when modified!

---
#### Issue metadata

* Issue type: sample-update

---
[Associated WorkItem - 37736](https://dev.azure.com/msft-skilling/Content/_workitems/edit/37736)

**Comment by jozefizso** [comment]
Yes, any code which relies on .NET 4.0 targeting is not usable nowadays as Microsoft remove all the SDKs for it. Sample should be updating with currently supported .NET libraries.

**Comment by VFerguson-haikurange** [comment]
Any updates on this? I have not been able to get MSTest to work with VSCode:
https://github.com/dotnet/samples/tree/main/core/getting-started/unit-testing-using-mstest

**Comment by IEvangelist** [comment]
I believe this has been addressed, we've been using the .NET Version Sweeper to track out-of-support projects and updating them monthly. Closing this... https://github.com/dotnet/samples/issues?q=is%3Aissue+label%3Adotnet-target-version+is%3Aclosed
