### ISSUE TITLE
core/diagnostics/DiagnosticScenarios not building since the NetwonsoftJson updat

### ISSUE THREAD

**Issue by EricStG** [dotnet/samples#5521]
## core/diagnostics/DiagnosticScenarios not building since the NetwonsoftJson update

Newtonsoft was updated to 7.0.0, but that version requires .Net 7
https://github.com/dotnet/samples/commit/ad2fb13bfe416b916c28f7b0a442e8bbf07e056f

---
#### Issue metadata

* Issue type: sample-update

**Comment by Merlissa09** [comment]
Not too sure if this is the best solution but works to temporarily solve the issue when running the sample projects while we await the update to .Net 7 for anyone reading this issue. Simply paste this into the terminal and then run the build/run commands.

`dotnet add package Microsoft.AspNetCore.Mvc.NewtonsoftJson --version 6.0.12`
