### ISSUE TITLE
Link Error When Building Native Static Libraries with NativeAOT

### ISSUE THREAD

**Issue by floydchenv** [dotnet/samples#6468]
**Target framework**
- [x] .NET Standard 8.0
Error during linking when building native lib with dotnet publish
dotnet publish -c Release -r win-x64 -p:PublishAot=true -p:NativeLib=Static

When I attempt to build my native library using dotnet publish /p:NativeLib=Static, I encounter an error during the C++ linking process. Could you please help me identify the issue? The specific error message is as follows:
`
LoadLibrary.cpp
linker generated manifest res * : fatal error LNK1241: resource file ETWCaptureLib.lib(ETWCaptureLib.obj) already specified
`
![289910464-54fbc2a1-eac9-40c4-8c7f-36e9ac93f1a4](https://github.com/dotnet/samples/assets/7371136/9427d851-6cee-42d4-ad6e-9099e4f91db3)
![289910524-0925a2c2-6f51-4e9d-92ac-d868309b2eae](https://github.com/dotnet/samples/assets/7371136/e539bbc2-5b48-4b26-924a-0cecd07eb88e)
![289910816-f7693a0b-684b-4961-831f-65b581976f57](https://github.com/dotnet/samples/assets/7371136/23b5ee95-9773-4585-af67-3df6b38e916e)
This is my project file
[STATIC_LIB_LINK_ERROR.zip](https://github.com/dotnet/samples/files/13649978/STATIC_LIB_LINK_ERROR.zip)

**Comment by hzgotb** [comment]
在csproj里加<IlcGenerateWin32Resources>false</IlcGenerateWin32Resources>
